### ISSUE TITLE
Can we get our Socks4 Proxies Back Please ?  <3

### ISSUE THREAD

**Issue by Hail2Hydra** [jetkai/proxy-list#4] opened 2022-01-15 15:00 UTC

**Comment by jetkai** [comment] 2022-01-16 06:52
@Hail2Hydra Ooh! I must of done something that broke this, sorry :) I will update this now.

**Comment by Hail2Hydra** [comment] 2022-01-16 22:49
@jetkai 

Take your Time !
Honestly im surprised i got an answer !
thanks for having enough time and respect to actually Reply to the thread !

**Comment by jetkai** [comment] 2022-01-22 07:55
@Hail2Hydra Sorry for the delay, should be fixed after the next run!

Issue was caused by upgrading JDK from 11 to 17 on the dedi and forgot I was using reflection for the SOCKS4 Socket (which has been deprecated since JDK 15.0.2).

Will be upgrading everything from Java's standard networking to Netty4 very to avoid this again in the future 😁! **(%90 there)**

**Comment by jetkai** [comment] 2022-01-22 07:57
**Code Ref:**

https://github.com/jetkai/ProxyBuilder/blob/cd7a20f42cac1975e1de2c06ed08741ecfa7ca2d/src/main/kotlin/spb/net/proxy/ProxyTester.kt#L155-L169

**Closed** 2022-01-22 08:09 UTC
Labels: bug, good first issue
